title: scattering and stats
logo: /assets/img/logo.png
email: andrew.mccluskey at bristol dot ac dot uk
description: navigating physics, chemistry, mathematics, and scientific computing
show_downloads: false
markdown: kramdown
color-scheme: auto
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji

# You can find fonts from https://iconify.design or https://fontawesome.com. Below is just an example illustrating how to use custom icons
sidebar:
  - name: blog
    icon: fa-solid fa-pen
    link: /blog/
  - name: resume
    icon: fa-solid fa-user
    link: https://nbviewer.org/github/arm61/resume/blob/master/resume.pdf
  - name: github
    icon: fa-brands fa-github
    link: https://github.com/arm61
  - name: strava
    icon: fa-solid fa-person-running
    link: https://www.strava.com/athletes/8500579
  - name: photo
    icon: fa-solid fa-camera
    link: /photo/

# https://github.com/github/pages-gem/issues/399#issuecomment-301827749
# When running locally, we run into the following error —
# GitHub Metadata: No GitHub API authentication could be found. Some fields may be missing or have incorrect data.
# adding this avoids it
github: [metadata]

